enableScripts: false
nmMode: hardlinks-global
nodeLinker: node-modules
npmMinimalAgeGate: 3d

npmPreapprovedPackages:
  - '@oxfmt/binding-*@0.45.0'
  - '@oxlint/binding-*@1.60.0'
  - '@rspack/binding*@2.0.0'
  - '@rspack/cli@2.0.0'
  - '@rspack/core@2.0.0'
  - '@tanstack/form-*'
  - '@tanstack/query-*'
  - '@tanstack/react-*'
  - '@tanstack/router-*'
  - '@tanstack/start-*'
  - '@voidzero-dev/vite-plus-*@0.1.18'
  - '@xcamp/config@2026.4.0'
  - oxfmt@0.45.0
  - oxlint@1.60.0
  - vite-plus@0.1.18

catalogs:
  orpc:
    '@orpc/client': 1.13.13
    '@orpc/server': 1.13.13
    '@orpc/standard-server-peer': 1.13.13
    '@orpc/tanstack-query': 1.13.13
  validation:
    zod: 4.3.6
