nmMode: hardlinks-global
nodeLinker: node-modules

catalogs:
  orpc:
    '@orpc/client': 1.13.13
    '@orpc/server': 1.13.13
    '@orpc/standard-server-peer': 1.13.13
    '@orpc/tanstack-query': 1.13.13
  validation:
    zod: 4.3.6
