enableScripts: false
nmMode: hardlinks-global
nodeLinker: node-modules
npmMinimalAgeGate: 3d

npmPreapprovedPackages:
  - '@dotenvx/dotenvx@1.59.1'
  - '@orpc/*'
  - '@oxfmt/*'
  - '@oxlint/*'
  - '@rspack/*'
  - '@tanstack/*'
  - '@voidzero-dev/vite-plus-*'
  - '@xcamp/*'
  - oxfmt
  - oxlint
  - pdfjs-dist@5.6.205
  - vite-plus

catalogs:
  orpc:
    '@orpc/client': 1.13.13
    '@orpc/server': 1.13.13
    '@orpc/standard-server-peer': 1.13.13
    '@orpc/tanstack-query': 1.13.13
  validation:
    zod: 4.3.6
